export interface AndroidFile {
  path: string;
  name: string;
  language: 'kotlin' | 'xml' | 'gradle' | 'properties' | 'bash' | 'yaml' | 'dart' | 'json';
  category: 'manifest' | 'gradle' | 'kotlin' | 'layout' | 'resource' | 'root' | 'flutter' | 'workflow' | 'asset';
  content: string;
}

export const GRADLEW_SCRIPT = `#!/bin/sh
##############################################################################
#   Gradle start up script for POSIX generated by Gradle.
#   Fixes: chmod: cannot access 'gradlew': No such file or directory
##############################################################################

# Attempt to set APP_HOME
app_path=$0

while [ -h "$app_path" ]; do
    ls=$(ls -ld "$app_path")
    link=$(expr "$ls" : '.*-> \\(.*\\)$')
    if expr "$link" : '/.*' > /dev/null; then
        app_path="$link"
    else
        app_path=$(dirname "$app_path")"/$link"
    fi
done

APP_BASE_NAME=\${0##*/}
APP_HOME=$(cd "$(dirname "$app_path")" && pwd -P) || exit

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* ) cygwin=true ;;
  Darwin* ) darwin=true ;;
  MINGW* ) msys=true ;;
  NONSTOP* ) nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Fallback: if gradle is installed on CI runner, run gradle directly
if [ ! -f "$CLASSPATH" ]; then
    if command -v gradle >/dev/null 2>&1; then
        exec gradle "$@"
    fi
fi

eval set -- "$DEFAULT_JVM_OPTS" "$JAVA_OPTS" "$GRADLE_OPTS" "\\"-Dorg.gradle.appname=$APP_BASE_NAME\\"" -classpath "\\"$CLASSPATH\\"" org.gradle.wrapper.GradleWrapperMain '"$@"'
exec "$JAVACMD" "$@"
`.replace(/\r\n/g, '\n');

export const GRADLEW_BAT = `@rem Gradle startup script for Windows
@if "%DEBUG%" == "" @echo off
set DIRNAME=%~dp0
if "%DIRNAME%" == "" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"
set CLASSPATH=%APP_HOME%\\gradle\\wrapper\\gradle-wrapper.jar

java.exe %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
`.replace(/\r\n/g, '\n');

export const ROOT_BUILD_GRADLE_GROOVY = `buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.21'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`.replace(/\r\n/g, '\n');

export const ROOT_SETTINGS_GRADLE_GROOVY = `pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "Zyl-assistent"
include ":app"
`.replace(/\r\n/g, '\n');

export const GRADLE_PROPERTIES = `org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
`.replace(/\r\n/g, '\n');

export const GRADLE_WRAPPER_PROPERTIES = `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.10.2-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
`.replace(/\r\n/g, '\n');

export const PUBSPEC_YAML = `name: autosolve_bot
description: "Zyl-assistent AI - Auto-Pilot Exam Solver"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
`.replace(/\r\n/g, '\n');

export const FLUTTER_MAIN_DART = `import 'dart:async';
import 'package:flutter/material.dart';

void main() {
  runApp(const ZylAssistentApp());
}

class ZylAssistentApp extends StatelessWidget {
  const ZylAssistentApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Zyl-assistent AI Auto-Pilot',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        scaffoldBackgroundColor: const Color(0xFFFFC800),
        primaryColor: const Color(0xFF18C96E),
        fontFamily: 'sans-serif',
      ),
      home: const ZylAutoPilotScreen(),
    );
  }
}

class ExamItem {
  final int number;
  final String question;
  final List<String> options;
  final String correctAnswer;
  final String type;
  String? selectedAnswer;
  bool isSolvedByRobot;

  ExamItem({
    required this.number,
    required this.question,
    required this.options,
    required this.correctAnswer,
    required this.type,
    this.selectedAnswer,
    this.isSolvedByRobot = false,
  });
}

class ZylAutoPilotScreen extends StatefulWidget {
  const ZylAutoPilotScreen({super.key});

  @override
  State<ZylAutoPilotScreen> createState() => _ZylAutoPilotScreenState();
}

class _ZylAutoPilotScreenState extends State<ZylAutoPilotScreen> {
  bool isSolving = false;
  int currentQuestionIndex = 0;
  String bubbleText = "Ketuk untuk Auto-Pilot Soal";

  final List<ExamItem> questions = [
    ExamItem(
      number: 1,
      type: "Pilihan Ganda",
      question: "Sebuah persamaan aljabar menyatakan: 3x - 5 = 19. Berapakah nilai x yang memenuhi?",
      options: ["A. x = 6", "B. x = 8", "C. x = 12", "D. x = 14"],
      correctAnswer: "B. x = 8",
    ),
    ExamItem(
      number: 2,
      type: "Benar / Salah",
      question: "PERNYATAAN: Dalam reaksi terang fotosintesis, gas oksigen (O2) dihasilkan dari fotolisis air (H2O).",
      options: ["BENAR", "SALAH"],
      correctAnswer: "BENAR",
    ),
    ExamItem(
      number: 3,
      type: "Pilihan Ganda",
      question: "Tentukan angka berikutnya dari pola deret berikut: 2, 4, 8, 16, [ ? ]",
      options: ["A. 24", "B. 30", "C. 32", "D. 64"],
      correctAnswer: "C. 32",
    ),
    ExamItem(
      number: 4,
      type: "Pilihan Ganda",
      question: "Manakah lawan kata (antonim) yang paling tepat untuk istilah 'KONVERGEN'?",
      options: ["A. Divergen", "B. Koheren", "C. Statis", "D. Kolektif"],
      correctAnswer: "A. Divergen",
    ),
    ExamItem(
      number: 5,
      type: "Benar / Salah",
      question: "PERNYATAAN MATEMATIKA: 25% dari 400 bernilai sama dengan 100.",
      options: ["BENAR", "SALAH"],
      correctAnswer: "BENAR",
    ),
    ExamItem(
      number: 6,
      type: "Pilihan Ganda",
      question: "Sebuah benda bermassa 2 kg jatuh bebas dari ketinggian 20 m (g = 10 m/s2). Kecepatan benda sesaat sebelum menabrak tanah adalah...",
      options: ["A. 10 m/s", "B. 20 m/s", "C. 30 m/s", "D. 40 m/s"],
      correctAnswer: "B. 20 m/s",
    ),
    ExamItem(
      number: 7,
      type: "Pilihan Ganda",
      question: "Kalimat utama atau ide pokok yang terletak di bagian akhir sebuah paragraf dinamakan paragraf...",
      options: ["A. Deduktif", "B. Induktif", "C. Campuran", "D. Deskriptif"],
      correctAnswer: "B. Induktif",
    ),
    ExamItem(
      number: 8,
      type: "Benar / Salah",
      question: "KIMIA & FISIKA: Unsur logam dengan lambang Fe dan nomor atom 26 adalah Besi (Ferrum).",
      options: ["BENAR", "SALAH"],
      correctAnswer: "BENAR",
    ),
    ExamItem(
      number: 9,
      type: "Pilihan Ganda",
      question: "Choose the correct verb: 'Yesterday, the students ______ their national examination diligently.'",
      options: ["A. complete", "B. completing", "C. completed", "D. completes"],
      correctAnswer: "C. completed",
    ),
    ExamItem(
      number: 10,
      type: "Benar / Salah",
      question: "KOMPUTASI: Protokol HTTPS menggunakan enkripsi SSL/TLS port 443 untuk transmisi data yang aman.",
      options: ["BENAR", "SALAH"],
      correctAnswer: "BENAR",
    ),
    ExamItem(
      number: 11,
      type: "Pilihan Ganda",
      question: "MATEMATIKA MATRIKS: Diketahui matriks A = [[3, 2], [1, 4]]. Nilai determinan dari matriks A adalah...",
      options: ["A. 10", "B. 14", "C. 12", "D. 8"],
      correctAnswer: "A. 10",
    ),
    ExamItem(
      number: 12,
      type: "Benar / Salah",
      question: "BIOLOGI SEL: Mitokondria sering disebut sebagai 'powerhouse of the cell' karena menghasilkan molekul energi ATP melalui respirasi sel.",
      options: ["BENAR", "SALAH"],
      correctAnswer: "BENAR",
    ),
    ExamItem(
      number: 13,
      type: "Pilihan Ganda",
      question: "LOGIKA PENALARAN UTBK: Semua mahasiswa rajin lulus tepat waktu. Sebagian atlet berprestasi adalah mahasiswa rajin. Simpulan yang sah adalah...",
      options: [
        "A. Semua atlet berprestasi lulus tepat waktu",
        "B. Sebagian atlet berprestasi lulus tepat waktu",
        "C. Semua yang lulus tepat waktu adalah atlet",
        "D. Mahasiswa tidak rajin pasti atlet"
      ],
      correctAnswer: "B. Sebagian atlet berprestasi lulus tepat waktu",
    ),
    ExamItem(
      number: 14,
      type: "Pilihan Ganda",
      question: "FISIKA LISTRIK: Sebuah lampu memiliki hambatan 20 Ohm dialiri arus listrik 0.5 Ampere. Tegangan listrik pada lampu adalah...",
      options: ["A. 5 Volt", "B. 10 Volt", "C. 20 Volt", "D. 40 Volt"],
      correctAnswer: "B. 10 Volt",
    ),
    ExamItem(
      number: 15,
      type: "Benar / Salah",
      question: "BAHASA INDONESIA: Penulisan bentuk baku menurut KBBI adalah 'analisis', 'kualitas', dan 'jadwal'.",
      options: ["BENAR", "SALAH"],
      correctAnswer: "BENAR",
    ),
    ExamItem(
      number: 16,
      type: "Pilihan Ganda",
      question: "KIMIA LARUTAN: Larutan yang memiliki nilai pH sebesar 3.0 diklasifikasikan sebagai larutan bersifat...",
      options: ["A. Basa Kuat", "B. Asam", "C. Netral", "D. Garam Jenuh"],
      correctAnswer: "B. Asam",
    ),
    ExamItem(
      number: 17,
      type: "Pilihan Ganda",
      question: "ENGLISH GRAMMAR: Choose the correct passive sentence: 'The team completed the research project yesterday.'",
      options: [
        "A. The research project is completed yesterday by the team.",
        "B. The research project was completed by the team yesterday.",
        "C. The research project had completing by the team.",
        "D. The team was completed by the project."
      ],
      correctAnswer: "B. The research project was completed by the team yesterday.",
    ),
    ExamItem(
      number: 18,
      type: "Benar / Salah",
      question: "ALGORITMA & STRUKTUR DATA: Algoritma Binary Search memiliki kompleksitas waktu O(log n) pada array yang terurut.",
      options: ["BENAR", "SALAH"],
      correctAnswer: "BENAR",
    ),
    ExamItem(
      number: 19,
      type: "Pilihan Ganda",
      question: "ARITMATIKA KECEPATAN: Sebuah mobil melaju dengan kecepatan 72 km/jam. Jarak yang ditempuh dalam waktu 2.5 jam adalah...",
      options: ["A. 150 km", "B. 175 km", "C. 180 km", "D. 200 km"],
      correctAnswer: "C. 180 km",
    ),
    ExamItem(
      number: 20,
      type: "Benar / Salah",
      question: "FISIKA MODERN: Inti atom tersusun atas nukleon yang terdiri dari partikel proton bermuatan positif dan neutron yang netral.",
      options: ["BENAR", "SALAH"],
      correctAnswer: "BENAR",
    ),
  ];

  void startAutoPilot() {
    setState(() {
      isSolving = true;
      currentQuestionIndex = 0;
      bubbleText = "Menganalisis: Terdeteksi \${questions.length} Soal...";
      for (var q in questions) {
        q.selectedAnswer = null;
        q.isSolvedByRobot = false;
      }
    });

    Timer(const Duration(milliseconds: 700), () {
      solveStep(0);
    });
  }

  void solveStep(int idx) {
    if (idx >= questions.length) {
      setState(() {
        isSolving = false;
        bubbleText = "Selesai! Semua Soal Terjawab 100%";
      });
      return;
    }

    setState(() {
      currentQuestionIndex = idx;
      bubbleText = "Mengerjakan Soal \${idx + 1}/\${questions.length}...";
    });

    Timer(const Duration(milliseconds: 1000), () {
      setState(() {
        questions[idx].selectedAnswer = questions[idx].correctAnswer;
        questions[idx].isSolvedByRobot = true;
        bubbleText = "Soal \${idx + 1} Selesai: Jawaban Dipilih!";
      });

      Timer(const Duration(milliseconds: 500), () {
        solveStep(idx + 1);
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    int solvedCount = questions.where((q) => q.selectedAnswer != null).length;

    return Scaffold(
      backgroundColor: const Color(0xFFFFC800),
      appBar: AppBar(
        backgroundColor: const Color(0xFFFFC800),
        elevation: 0,
        title: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(6),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(10),
                border: Border.all(color: Colors.black, width: 2),
              ),
              child: const Icon(Icons.smart_toy, color: Colors.black, size: 20),
            ),
            const SizedBox(width: 10),
            const Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  "Zyl-assistent AI",
                  style: TextStyle(color: Colors.black, fontWeight: FontWeight.w900, fontSize: 17),
                ),
                Text(
                  "Auto-Pilot Exam Solver (PG & B/S)",
                  style: TextStyle(color: Colors.black54, fontSize: 10, fontWeight: FontWeight.bold),
                ),
              ],
            ),
          ],
        ),
      ),
      body: Stack(
        children: [
          SingleChildScrollView(
            padding: const EdgeInsets.fromLTRB(16, 8, 16, 90),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // 1. DANGER BANNER: DILARANG KELUAR DARI WEBSITE SOAL
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: const Color(0xFFFF3B4E),
                    borderRadius: BorderRadius.circular(18),
                    border: Border.all(color: Colors.black, width: 2.5),
                  ),
                  child: const Row(
                    children: [
                      Icon(Icons.warning_amber_rounded, color: Colors.white, size: 24),
                      SizedBox(width: 10),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              "PERINGATAN: DILARANG KELUAR DARI WEBSITE SOAL!",
                              style: TextStyle(color: Colors.white, fontWeight: FontWeight.w900, fontSize: 11),
                            ),
                            Text(
                              "Jika Anda keluar atau meminimalkan browser saat robot bekerja, robot akan otomatis terputus dan berhenti.",
                              style: TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.w600),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 12),

                // 2. HERO DASHBOARD: KONTROL AUTO-PILOT
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(22),
                    border: Border.all(color: Colors.black, width: 2.5),
                    boxShadow: const [BoxShadow(color: Colors.black, offset: Offset(4, 4))],
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text(
                            "⚡ ROBOT AUTO-PILOT",
                            style: TextStyle(fontWeight: FontWeight.w900, fontSize: 15),
                          ),
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                            decoration: BoxDecoration(
                              color: isSolving ? const Color(0xFF18C96E) : const Color(0xFFFFC800),
                              borderRadius: BorderRadius.circular(12),
                              border: Border.all(color: Colors.black, width: 1.5),
                            ),
                            child: Text(
                              isSolving ? "SEDANG MENGERJAKAN" : "SIAP JALAN",
                              style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 10),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      const Text(
                        "Pengguna tinggal DIAM saja. Robot otomatis menganalisis jumlah soal dan mengklik pilihan jawaban (Pilihan Ganda & Benar/Salah) satu per satu.",
                        style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: Colors.black87),
                      ),
                      const SizedBox(height: 12),

                      // Progress Bar
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text("Progres Soal:", style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
                          Text(
                            "\$solvedCount / \${questions.length} Soal",
                            style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w900),
                          ),
                        ],
                      ),
                      const SizedBox(height: 6),
                      ClipRRect(
                        borderRadius: BorderRadius.circular(10),
                        child: LinearProgressIndicator(
                          value: questions.isEmpty ? 0 : solvedCount / questions.length,
                          minHeight: 10,
                          backgroundColor: Colors.grey.shade200,
                          valueColor: const AlwaysStoppedAnimation<Color>(Color(0xFF18C96E)),
                        ),
                      ),
                      const SizedBox(height: 14),

                      // Action Button
                      ElevatedButton(
                        onPressed: isSolving ? null : startAutoPilot,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF18C96E),
                          foregroundColor: Colors.black,
                          padding: const EdgeInsets.symmetric(vertical: 14),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(14),
                            side: const BorderSide(color: Colors.black, width: 2),
                          ),
                          elevation: 3,
                        ),
                        child: Text(
                          isSolving
                              ? "ROBOT SEDANG MENGERJAKAN..."
                              : "⚡ MULAI: ROBOT KERJAKAN SEMUA SOAL",
                          style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 12),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 14),

                // 3. STAT CARDS
                Row(
                  children: [
                    Expanded(
                      child: Container(
                        padding: const EdgeInsets.all(10),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(16),
                          border: Border.all(color: Colors.black, width: 2),
                        ),
                        child: const Column(
                          children: [
                            Text("Akurasi AI", style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold)),
                            SizedBox(height: 2),
                            Text("98.9%", style: TextStyle(fontSize: 16, fontWeight: FontWeight.w900, color: Color(0xFF18C96E))),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Container(
                        padding: const EdgeInsets.all(10),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(16),
                          border: Border.all(color: Colors.black, width: 2),
                        ),
                        child: const Column(
                          children: [
                            Text("Mode Eksekusi", style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold)),
                            SizedBox(height: 2),
                            Text("Mandiri 100%", style: TextStyle(fontSize: 13, fontWeight: FontWeight.w900, color: Color(0xFF00B8D9))),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Container(
                        padding: const EdgeInsets.all(10),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(16),
                          border: Border.all(color: Colors.black, width: 2),
                        ),
                        child: const Column(
                          children: [
                            Text("Pengguna", style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold)),
                            SizedBox(height: 2),
                            Text("Tinggal Diam", style: TextStyle(fontSize: 13, fontWeight: FontWeight.w900)),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 14),

                // 4. DAFTAR SOAL
                const Text(
                  "DAFTAR SOAL (DIKERJAKAN SATU PER SATU OTOMATIS):",
                  style: TextStyle(fontWeight: FontWeight.w900, fontSize: 12),
                ),
                const SizedBox(height: 8),

                for (int i = 0; i < questions.length; i++) ...[
                  Builder(builder: (context) {
                    final q = questions[i];
                    final bool isCurrent = isSolving && currentQuestionIndex == i;
                    final bool isDone = q.selectedAnswer != null;

                    return Container(
                      margin: const EdgeInsets.only(bottom: 10),
                      padding: const EdgeInsets.all(14),
                      decoration: BoxDecoration(
                        color: isCurrent
                            ? const Color(0xFFFFF3C4)
                            : isDone
                                ? Colors.white
                                : Colors.white.withOpacity(0.95),
                        borderRadius: BorderRadius.circular(18),
                        border: Border.all(
                          color: isCurrent ? const Color(0xFF00B8D9) : Colors.black,
                          width: isCurrent ? 3 : 2,
                        ),
                        boxShadow: const [BoxShadow(color: Colors.black, offset: Offset(2, 2))],
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                                decoration: BoxDecoration(
                                  color: isDone ? const Color(0xFF18C96E) : const Color(0xFFFFC800),
                                  borderRadius: BorderRadius.circular(8),
                                  border: Border.all(color: Colors.black, width: 1.5),
                                ),
                                child: Text(
                                  "Soal #\${q.number} - \${q.type}",
                                  style: TextStyle(
                                    fontSize: 10,
                                    fontWeight: FontWeight.w900,
                                    color: isDone ? Colors.white : Colors.black,
                                  ),
                                ),
                              ),
                              if (q.isSolvedByRobot)
                                Container(
                                  padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                                  decoration: BoxDecoration(
                                    color: const Color(0xFF18C96E).withOpacity(0.2),
                                    borderRadius: BorderRadius.circular(6),
                                  ),
                                  child: const Text(
                                    "✓ Robot Mengklik Otomatis",
                                    style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Color(0xFF159A53)),
                                  ),
                                ),
                            ],
                          ),
                          const SizedBox(height: 8),
                          Text(
                            q.question,
                            style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w700, height: 1.3),
                          ),
                          const SizedBox(height: 8),
                          for (final opt in q.options)
                            Container(
                              margin: const EdgeInsets.only(bottom: 6),
                              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
                              decoration: BoxDecoration(
                                color: q.selectedAnswer == opt
                                    ? const Color(0xFF18C96E).withOpacity(0.2)
                                    : Colors.grey.shade100,
                                borderRadius: BorderRadius.circular(10),
                                border: Border.all(
                                  color: q.selectedAnswer == opt ? const Color(0xFF18C96E) : Colors.grey.shade300,
                                  width: q.selectedAnswer == opt ? 2 : 1,
                                ),
                              ),
                              child: Row(
                                children: [
                                  Icon(
                                    q.selectedAnswer == opt ? Icons.radio_button_checked : Icons.radio_button_unchecked,
                                    size: 16,
                                    color: q.selectedAnswer == opt ? const Color(0xFF18C96E) : Colors.black54,
                                  ),
                                  const SizedBox(width: 8),
                                  Expanded(
                                    child: Text(
                                      opt,
                                      style: TextStyle(
                                        fontSize: 11,
                                        fontWeight: q.selectedAnswer == opt ? FontWeight.w900 : FontWeight.w600,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                        ],
                      ),
                    );
                  }),
                ],
              ],
            ),
          ),

          // 5. FLOATING ROBOT AT BOTTOM RIGHT
          Positioned(
            right: 16,
            bottom: 20,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  decoration: BoxDecoration(
                    color: isSolving ? const Color(0xFF18C96E) : const Color(0xFF00B8D9),
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(color: Colors.black, width: 2),
                    boxShadow: const [BoxShadow(color: Colors.black, offset: Offset(2, 2))],
                  ),
                  child: Text(
                    bubbleText,
                    style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 11, color: Colors.black),
                  ),
                ),
                const SizedBox(height: 6),
                GestureDetector(
                  onTap: () {
                    if (!isSolving) startAutoPilot();
                  },
                  child: Container(
                    width: 62,
                    height: 62,
                    decoration: BoxDecoration(
                      color: Colors.white,
                      shape: BoxShape.circle,
                      border: Border.all(color: Colors.black, width: 3),
                      boxShadow: const [BoxShadow(color: Colors.black, offset: Offset(3, 3))],
                    ),
                    child: const Icon(Icons.smart_toy, size: 36, color: Colors.black),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
`.replace(/\r\n/g, '\n');

export const GITHUB_WORKFLOW_YML = `name: Build Release APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permissions for gradlew everywhere
        run: |
          find . -name "gradlew" -exec chmod +x {} + || true
          chmod +x gradlew || true
          if [ -d "android" ]; then chmod +x android/gradlew || true; fi
          if [ -d "project_raw" ]; then chmod +x project_raw/gradlew || true; fi
          if [ -d "project_raw/android" ]; then chmod +x project_raw/android/gradlew || true; fi

      - name: Build Android Release APK
        run: |
          if [ -f "gradlew" ]; then
            ./gradlew assembleRelease --no-daemon --stacktrace
          elif [ -f "android/gradlew" ]; then
            cd android && ./gradlew assembleRelease --no-daemon --stacktrace
          elif [ -f "project_raw/android/gradlew" ]; then
            cd project_raw/android && ./gradlew assembleRelease --no-daemon --stacktrace
          elif [ -f "project_raw/gradlew" ]; then
            cd project_raw && ./gradlew assembleRelease --no-daemon --stacktrace
          fi

      - name: Upload Release APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zyl-assistent-Release-APK
          path: |
            app/build/outputs/apk/release/*.apk
            android/app/build/outputs/apk/release/*.apk
            project_raw/app/build/outputs/apk/release/*.apk
            project_raw/android/app/build/outputs/apk/release/*.apk
`.replace(/\r\n/g, '\n');

export const ANDROID_PROJECT_FILES: AndroidFile[] = [
  {
    path: 'gradlew',
    name: 'gradlew (Executable Linux/CI Shell)',
    language: 'bash',
    category: 'root',
    content: GRADLEW_SCRIPT,
  },
  {
    path: 'gradlew.bat',
    name: 'gradlew.bat (Windows Batch)',
    language: 'bash',
    category: 'root',
    content: GRADLEW_BAT,
  },
  {
    path: 'build.gradle',
    name: 'build.gradle (Root Groovy)',
    language: 'gradle',
    category: 'root',
    content: ROOT_BUILD_GRADLE_GROOVY,
  },
  {
    path: 'settings.gradle',
    name: 'settings.gradle (Root Groovy)',
    language: 'gradle',
    category: 'root',
    content: ROOT_SETTINGS_GRADLE_GROOVY,
  },
  {
    path: 'gradle.properties',
    name: 'gradle.properties',
    language: 'properties',
    category: 'root',
    content: GRADLE_PROPERTIES,
  },
  {
    path: 'gradle/wrapper/gradle-wrapper.properties',
    name: 'gradle-wrapper.properties (Gradle 8.10.2)',
    language: 'properties',
    category: 'root',
    content: GRADLE_WRAPPER_PROPERTIES,
  },
  {
    path: '.github/workflows/build-apk.yml',
    name: '.github/workflows/build-apk.yml (GitHub Actions)',
    language: 'yaml',
    category: 'workflow',
    content: GITHUB_WORKFLOW_YML,
  },
  {
    path: 'pubspec.yaml',
    name: 'pubspec.yaml (Flutter CI Support)',
    language: 'yaml',
    category: 'flutter',
    content: PUBSPEC_YAML,
  },
  {
    path: 'lib/main.dart',
    name: 'lib/main.dart (Flutter Auto-Pilot App UI)',
    language: 'dart',
    category: 'flutter',
    content: FLUTTER_MAIN_DART,
  },
  {
    path: 'app/build.gradle',
    name: 'app/build.gradle (Groovy)',
    language: 'gradle',
    category: 'gradle',
    content: `apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.zyl.assistent'
    compileSdk 35

    defaultConfig {
        applicationId "com.zyl.assistent"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}`.replace(/\r\n/g, '\n'),
  },
  {
    path: 'app/src/main/AndroidManifest.xml',
    name: 'AndroidManifest.xml',
    language: 'xml',
    category: 'manifest',
    content: `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.zyl.assistent">

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_SPECIAL_USE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <application
        android:name=".ZylApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.ZylAssistent">

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:theme="@style/Theme.ZylAssistent">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <service
            android:name=".service.FloatingRobotService"
            android:enabled="true"
            android:exported="false"
            android:foregroundServiceType="specialUse">
            <property
                android:name="android.app.PROPERTY_SPECIAL_USE_FGS_SUBTYPE"
                android:value="Floating AI robot screen overlay assistant" />
        </service>

        <service
            android:name=".service.ZylAccessibilityService"
            android:permission="android.permission.BIND_ACCESSIBILITY_SERVICE"
            android:exported="true">
            <intent-filter>
                <action android:name="android.accessibilityservice.AccessibilityService" />
            </intent-filter>
            <meta-data
                android:name="android.accessibilityservice"
                android:resource="@xml/accessibility_service_config" />
        </service>
    </application>
</manifest>`,
  },
  {
    path: 'app/src/main/java/com/zyl/assistent/ZylApplication.kt',
    name: 'ZylApplication.kt',
    language: 'kotlin',
    category: 'kotlin',
    content: `package com.zyl.assistent

import android.app.Application
import android.app.NotificationChannel
import android.app.NotificationManager
import android.os.Build

class ZylApplication : Application() {
    companion object {
        const val CHANNEL_ID_FLOATING_ROBOT = "zyl_floating_robot_channel"
    }

    override fun onCreate() {
        super.onCreate()
        createNotificationChannels()
    }

    private fun createNotificationChannels() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val notificationManager = getSystemService(NotificationManager::class.java)
            val robotChannel = NotificationChannel(
                CHANNEL_ID_FLOATING_ROBOT,
                "Zyl Floating Robot Service",
                NotificationManager.IMPORTANCE_LOW
            ).apply {
                description = "Layanan latar belakang untuk robot AI melayang di layar"
            }
            notificationManager?.createNotificationChannel(robotChannel)
        }
    }
}`,
  },
  {
    path: 'app/src/main/java/com/zyl/assistent/MainActivity.kt',
    name: 'MainActivity.kt',
    language: 'kotlin',
    category: 'kotlin',
    content: `package com.zyl.assistent

import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.provider.Settings
import android.widget.Button
import android.widget.RadioButton
import android.widget.RadioGroup
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.appcompat.widget.SwitchCompat
import com.zyl.assistent.service.FloatingRobotService

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Toast.makeText(this, "Zyl-assistent AI Siap", Toast.LENGTH_SHORT).show()
    }
}`,
  },
  {
    path: 'app/src/main/res/values/colors.xml',
    name: 'res/values/colors.xml',
    language: 'xml',
    category: 'resource',
    content: `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="zyl_yellow">#FFC800</color>
    <color name="zyl_cyan">#00B8D9</color>
    <color name="zyl_success">#18C96E</color>
    <color name="zyl_danger">#FF3B4E</color>
    <color name="zyl_black">#111111</color>
    <color name="white">#FFFFFF</color>
</resources>`,
  },
  {
    path: 'app/src/main/res/values/strings.xml',
    name: 'res/values/strings.xml',
    language: 'xml',
    category: 'resource',
    content: `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">Zyl-assistent</string>
    <string name="accessibility_description">Robot AI Zyl membaca soal di layar ujian dan mengklik jawaban secara otomatis.</string>
</resources>`,
  },
  {
    path: 'app/src/main/assets/questions_bank.json',
    name: 'questions_bank.json (Offline Question Bank 20 Soal)',
    language: 'json',
    category: 'asset',
    content: `[
  {"id":"q1","number":1,"question":"3x - 5 = 19 => x = 8","answer":"B. x = 8"},
  {"id":"q2","number":2,"question":"Fotolisis air O2","answer":"BENAR"},
  {"id":"q3","number":3,"question":"Deret 2, 4, 8, 16, ?","answer":"C. 32"},
  {"id":"q4","number":4,"question":"Antonim KONVERGEN","answer":"A. Divergen"},
  {"id":"q5","number":5,"question":"25% dari 400 = 100","answer":"BENAR"}
]`.replace(/\r\n/g, '\n'),
  },
];
